pipeline:
    build:
        image: hashicorp/terraform:light
        commands:
            - terraform version
            - terraform validate -check-variables="false"
            - terraform fmt -check=true
